name: Daily Sustainability News Update

on:
  schedule:
    - cron: '0 6 * * *'   # runs daily at 06:00 UTC
  workflow_dispatch:      # allows manual trigger from Actions UI

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sustainability script
        run: |
          python sustainability_news.py
