name: Daily Sustainability News Update

# Run every day at 08:00 UTC
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:  # allows manual trigger

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Needed for push

      # 2️⃣ Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install lxml[html_clean]

      # 4️⃣ Run the news script
      - name: Run sustainability_updates.py
        run: |
          python sustainability_updates.py

      # 5️⃣ Commit and push updated JSON (filtered_articles.json)
      - name: Commit & push updated JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add filtered_articles.json
          git commit -m "Automated update of sustainability articles $(date +'%Y-%m-%d')"
          git push
        continue-on-error: true  # avoids failure if no changes
