name: Daily Sustainability News Update

on:
  schedule:
    - cron: "0 8 * * *"  # Run every day at 08:00 UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # 2️⃣ Set up Python 3.12
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir lxml_html_clean

      # 4️⃣ Ensure nltk punkt for newspaper3k
      - name: Ensure nltk punkt (safe)
        run: |
          python - <<'PY'
          import nltk
          try:
              nltk.data.find("tokenizers/punkt")
              print("nltk punkt already present")
          except LookupError:
              nltk.download("punkt")
              print("Downloaded nltk punkt")
          PY

      # 5️⃣ Run sustainability update script
      - name: Run the news update process
        run: |
          echo "🚀 Running sustainability_updates.py..."
          python sustainability_updates.py
        continue-on-error: false  # Fail visibly if script errors

      # 6️⃣ Commit and push updated JSON results
      - name: Commit & push updated outputs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add filtered_articles.json clustered_articles.json summarized_articles.json || true
          git commit -m "Automated sustainability update: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
        continue-on-error: true
